app:
  host: http://127.0.0.1:5000
  dev_gateway: http://10.182.200.90:9009/gateway
  dev2_gateway: http://10.182.211.40:9008/gateway
  sit1_gateway: http://10.182.210.131:9009/gateway
  sit2_gateway: http://10.182.211.103:9009/gateway
  sit3_gateway: http://10.182.211.179:9009/gateway
  sit4_gateway: http://10.182.212.101:9009/gateway
  uat_gateway: http://10.182.220.105:9009/gateway
  uat_mufc: http://10.182.220.105:9009/mucfc/uloan/merchCreditApply
  sit2_mufc: http://10.182.211.103:9009/mucfc/uloan/merchCreditApply
  query: 10.182.220.105:9009/mucfc/uloan/merchQueryApplyResult
  encrvption: http://10.182.211.73:8091/mucf/encryption
  decryption: http://22.186.80.8:8888/mucf/decrypt
  vip_encrvption: http://10.182.200.116:8091/encryption
  vip_apply: http://10.182.211.103:9009/bocxf/credit/openAccount

user:
  account: admin@admin.com
  password: 111111

report:
  report_folder: report
  email:
    email: tangpeng@sunline.cn
    password:
    to_list:
      - 17366199527@163.com
      - 2500298621@qq.com

walnuts run: